In [1]:
import numpy as np
import cv2

In [6]:
rutaDogs = 'cat_dog_100/train/dog'


In [7]:
from os import walk

dogTrain = []
for (dirpath, dirnames, filenames) in walk(rutaDogs):
    dogTrain.extend(filenames)
    break


In [9]:
print(f'{rutaDogs}/{dogTrain[0]}')

cat_dog_100/train/dog/dog.10000.jpg


In [109]:
tamano = 500
sizeVentana = 16
tamano = int(tamano/sizeVentana)*sizeVentana

In [101]:
n = 9
imagen = cv2.imread(f'{rutaDogs}/{dogTrain[n]}')
imagen2 = resize_image(imagen, sizeVentana, tamano, True)
cv2.imshow(f'{dogTrain[n]}a', imagen2)
cv2.imshow(f'{dogTrain[n]}', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
cv2.resize??

In [75]:
def recorta_imagen(imagen, n):
    """
    Esta función recibe una imagen y un tamaño n y recorta la imagen de tal manera que el número final de filas/columnas 
    sea múltiplo de n. La funció debe recortar las filas de la derecha/abajo.
    """
    size = np.min([int(imagen.shape[0]/n)*n, int(imagen.shape[1]/n)*n])
    return imagen[:size, :size]

In [95]:
def resize_image(imagen, sizeVentana, tamano, recorta=False):
    if(recorta): imagen = recorta_imagen(imagen, sizeVentana)
    imagen2 = cv2.resize(imagen, [tamano,tamano])
    return imagen2

In [38]:
def ventana_a_decimal(ventana_binario):
    return ventana_binario[0,0]*2**7+ventana_binario[0,1]*2**6+ventana_binario[0,2]*2**5+ventana_binario[1,2]*2**4+ventana_binario[2,2]*2**3+ventana_binario[2,1]*2**2+ventana_binario[2,0]*2+ventana_binario[1,0]

In [52]:
def transforma_bloque(celda):
    celda_ampliada = cv2.copyMakeBorder(celda, 1, 1, 1, 1, cv2.BORDER_REPLICATE)
    celda2 = np.empty(celda.shape)
    for i in range(1, celda.shape[0]+1):
        for j in range(1, celda.shape[1]+1):
            ventana = celda_ampliada[i-1:i+2, j-1:j+2]
            ventana2 = np.zeros(ventana.shape)
            pixel_central = ventana[1,1]
            ventana2[ventana>pixel_central] = 1
            celda2[i-1,j-1] = ventana_a_decimal(ventana2)
    return celda2

In [106]:
def transforma_imagen(imagen, sizeVentana, tamano):
    imagen = resize_image(imagen, sizeVentana, tamano, True)
    imagen2 = np.zeros(imagen.shape)
    a = int(imagen.shape[0]/sizeVentana)
    for i in range(a):
        for j in range(a):
            celda = imagen[i*sizeVentana:(i+1)*sizeVentana,j*sizeVentana:(j+1)*sizeVentana]
            imagen2[i*sizeVentana:(i+1)*sizeVentana,j*sizeVentana:(j+1)*sizeVentana] = transforma_bloque(celda)
    return imagen2

In [110]:
n = 2
imagen = cv2.imread(f'{rutaDogs}/{dogTrain[n]}')
imagen2 = transforma_imagen(imagen, sizeVentana, tamano)
cv2.imshow(f'{dogTrain[n]}', imagen)
cv2.imshow(f'{dogTrain[n]}_transfrmada', np.uint8(imagen2))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array)
print(recorta_imagen(array,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
